apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-blob-storage
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
