name: Deploy AKS Store Demo - Self-Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-aks-final
  CLUSTER_NAME: aks-final-cluster
  LOCATION: eastus

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login with Managed Identity
        run: |
          # Login using the managed identity assigned to the VM
          az login --identity --client-id 893a4871-96d2-4a32-b6c6-954045688408

      - name: Create AKS Cluster
        run: |
          # Create AKS cluster if it doesn't exist
          az aks create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} \
            --node-count 1 \
            --enable-addons monitoring \
            --generate-ssh-keys \
            --location ${{ env.LOCATION }} \
            --yes

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy AKS Store Demo
        run: |
          # Apply the store demo
          kubectl apply -f https://raw.githubusercontent.com/Azure-Samples/aks-store-demo/main/aks-store-demo.yaml

          # Wait for deployments to be ready
          kubectl wait --for=condition=available --timeout=300s deployment/aks-store-demo-frontend -n aks-store-demo
          kubectl wait --for=condition=available --timeout=300s deployment/aks-store-demo-backend -n aks-store-demo

      - name: Get Service URLs
        run: |
          echo "=== AKS Store Demo Deployment Complete ==="
          echo "Frontend URL:"
          kubectl get service aks-store-demo-frontend -n aks-store-demo -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          echo ""
          echo "Backend URL:"
          kubectl get service aks-store-demo-backend -n aks-store-demo -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          echo ""
          echo "=== Pod Status ==="
          kubectl get pods -n aks-store-demo
